USE DataWarehouseAnalytics;

-- Question 1: Find total customers by country
SELECT
    country,
    COUNT(DISTINCT customer_key) AS total_customers
FROM dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Question 2: Find total customers by gender
SELECT
    gender,
    COUNT(DISTINCT customer_key) AS total_customers
FROM dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Question 3: Find total products by category
SELECT
    category,
    COUNT(DISTINCT product_key) AS total_products
FROM dim_products
GROUP BY category
ORDER BY total_products DESC;

-- Question 4: What is the average cost in each category?
SELECT
    category,
    AVG(cost) AS avg_cost,
    MIN(cost) AS min_cost,
    MAX(cost) AS max_cost
FROM dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- Question 5: What is the total revenue generated for each category?
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM fact_sales f
JOIN dim_products p ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Question 6: Find total revenue generated by each customer
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    c.country,
    SUM(f.sales_amount) AS total_revenue
FROM fact_sales f
JOIN dim_customers c ON f.customer_key = c.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name,
    c.country
ORDER BY total_revenue DESC;

-- Question 7: What is the distribution of sold items across countries?
SELECT
    c.country,
    SUM(f.quantity)                AS total_items_sold,
    COUNT(DISTINCT f.order_number) AS total_orders,
    SUM(f.sales_amount)            AS total_revenue
FROM fact_sales f
JOIN dim_customers c ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_items_sold DESC;